### ISSUE TITLE
Error during initialization of module `Singular_jll` on Julia 1.4 - macOS-latest - x64

### ISSUE THREAD

**Issue by mohamed-barakat** [oscar-system/Singular.jl#275]
The following GitHub test

https://github.com/homalg-project/HomalgProject.jl/pull/64/checks?check_run_id=1210910822

fails for the reason

```
Incompatible library version: libfactory.dylib requires version 8.0.0 or later, but libmpfr.dylib provides version 7.0.0
```

**Comment by fingolfin** [comment]
Yes, this is the same issue we had with GMP_jll just now with MPFR_jll... I am aware of it and will take care of it tomorrow.

**Comment by mohamed-barakat** [comment]
Good, thanks Max.

**Comment by fingolfin** [comment]
See https://github.com/JuliaPackaging/Yggdrasil/pull/1748

**Comment by fingolfin** [comment]
We just released a fresh Singular_jll, please give it a try (required a fix to https://github.com/JuliaPackaging/BinaryBuilderBase.jl/issues/45 which I made in https://github.com/JuliaPackaging/BinaryBuilderBase.jl/pull/51 ... )

**Comment by mohamed-barakat** [comment]
Thank you very much. The test is still failing:

https://github.com/homalg-project/HomalgProject.jl/pull/64/checks?check_run_id=1221096737

**Comment by fingolfin** [comment]
That build did not use the latest Singular_jll -- can you try once more?

**Comment by fingolfin** [comment]
Ah no wait a bit longer -- of course https://github.com/JuliaRegistries/General/pull/22524/files still needs to be merged first

**Comment by mohamed-barakat** [comment]
> Ah no wait a bit longer -- of course https://github.com/JuliaRegistries/General/pull/22524/files still needs to be merged first

I was reluctant to write shall I wait a bit longer not to be misunderstood 😂

**Comment by fingolfin** [comment]
No try again

**Comment by mohamed-barakat** [comment]
Worked:

https://github.com/homalg-project/HomalgProject.jl/pull/64/checks?check_run_id=1221311051

Thank you very much, Max.
