### ISSUE TITLE
bad behaviour wrt division by zero

### ISSUE THREAD

**Issue by tthsqe12** [oscar-system/Singular.jl#368]
The first error message is fine with me. The lack of error messages for the next two is not fine.
```julia
julia> using Singular

julia> R,(x,y,z)=PolynomialRing(QQ,["x","y","z"]);

julia> (x-x)//(y-y)
ERROR: DivideError: integer division error

julia> F,(x,y,z)=FunctionField(QQ,["x","y","z"]);

julia> (x-x)//(y-y)
0

julia> (x+x)//(y-y)
   ? div by 0

signal (11): Segmentation fault
```

**Comment by hannes14** [comment]
Should be fixed with https://github.com/Singular/Singular/commit/19ee5eb33e0ea7b7b2733aee435dc677eb23f478
Now, beside the error message, always a 0 is returned in this case.

**Comment by fingolfin** [comment]
@hannes14 the commit you mention is now included in the Singular used by Singular.jl, but this crash still happens anyway.

Also, that ` (x-x)//(y-y)` returns 0 still is weird, not to say: wrong, isn't it? 0/0 should raise an error...?

**Comment by 8d1h** [comment]
Hi! There is another weird issue related to division by zero: once a such division is performed inside a polynomial ring, `std` will no longer function for *all* rings and always returns 0...
```julia
julia> R, (x,) = PolynomialRing(QQ, ["x"])
(Singular Polynomial Ring (QQ),(x),(dp(1),C), spoly{n_Q}[x])

julia> div(R(), R())
   ? div. by 0
0

julia> std(Ideal(R, R(1)))
Singular Ideal over Singular Polynomial Ring (QQ),(x),(dp(1),C) with generators (0)

julia> S, (x,y) = PolynomialRing(QQ, ["x", "y"])
(Singular Polynomial Ring (QQ),(x,y),(dp(2),C), spoly{n_Q}[x, y])

julia> std(Ideal(S, x+y))
Singular Ideal over Singular Polynomial Ring (QQ),(x,y),(dp(2),C) with generators (0)
```

**Comment by thofma** [comment]
ping @hannes14

**Comment by tthsqe12** [comment]
I think we probably have to clear some gloval error flag here.

**Comment by hannes14** [comment]
Yes, the flag errorreported must be reset to 0.
This can be done in the routine which displays the error
- can be a change in libsingular-julia

**Comment by tthsqe12** [comment]
I am planning on handling this like this
```
julia> R, (x,) = PolynomialRing(QQ, ["x"])
(Singular Polynomial Ring (QQ),(x),(dp(1),C), spoly{n_Q}[x])

julia> div(R(), R())
ERROR: div. by 0
Stacktrace:
 [1] error(s::CxxWrap.StdLib.StdStringAllocated)
   @ Base ./error.jl:33
 [2] check_error
   @ ~/.julia/dev/Singular/src/LibSingular.jl:16 [inlined]
 [3] div(x::spoly{n_Q}, y::spoly{n_Q})
   @ Singular ~/.julia/dev/Singular/src/poly/poly.jl:591
 [4] top-level scope
   @ REPL[3]:1

julia> iszero(std(Ideal(R, R(1))))
false
```
