### ISSUE TITLE
(::N_AlgExtField)(::BigInt) is broken

### ISSUE THREAD

**Issue by tthsqe12** [oscar-system/Singular.jl#456]
@hannes14 The problem seems to be that `libpolys/polys/ext_fields/algext.cc` has no entry for `InitMPZ` hence everying goes through `number naInit(long i, const coeffs cf)`.
This not correct: we cannot be truncating `BigInt`'s to `Int`'s.

```julia
julia> using Singular

julia> F, (a,) = FunctionField(QQ, ["a"])
(Function Field over Rational Field with transcendence basis n_transExt[a], n_transExt[a])

julia> F, a = AlgebraicExtensionField(F, a^2 + 1)
(Algebraic Extension of Rational Field with defining equation a^2 + 1, a)

julia> F(BigInt(3)^100)
n_InitMPZ called
b = 515377520732011331036461129765621272702107522001
cf = CxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.coeffs}(Ptr{Singular.libSingular.coeffs} @0x00007f0a2e247cd0)
naInit called i = 6238749191317230545
r = CxxWrap.CxxWrapCore.CxxPtr{Singular.libSingular.number}(Ptr{Singular.libSingular.number} @0x00007f0a2e2441f8)
6238749191317230545

julia> mod(BigInt(3)^100, BigInt(2)^63)
6238749191317230545
```

**Comment by hannes14** [comment]
fixed with https://github.com/Singular/Singular/commit/528b7b158ad3a42e4835ade5d339a2fd1a384fda

**Comment by tthsqe12** [comment]
Thanks. We will have this in a later version of singular.jl.

**Comment by tthsqe12** [comment]
We have new singular binaries and it turns out that this still doesn't work.
To start, in libsingular_julia_jll we have (as in `jjSetMinpoly`):
```
  coeffs new_cf = nInitChar(n_algExt, &A);
```
That is, we are using `n_algExt` and *not* `n_polyExt`. Now 528b7b1 adds the line
```
cf->cfInitMPZ      = naInitMPZ;
```
to `n2pInitChar` but not to `naInitChar`?

**Comment by hannes14** [comment]
right, fixed with be5cfa7e7056fe594fbdb2d804b8d68f0869dda9
